"""Real producer fixture through the existing public SDK jobs API."""

import json
from pathlib import Path

import pytest

from genflux.jobs import JobsClient
from genflux.models.assessment_contract import parse_assessment_bundle


def fixture():
    """Load a fictional bundle generated by the Platform extraction engine."""
    return json.loads((Path(__file__).parent / "fixtures/extraction-assessment-v3.json").read_text())


class Transport:
    """Record public SDK requests without contacting Platform."""

    def __init__(self, bundle):
        self.bundle = bundle
        self.requests = []

    def post(self, path, *, json):
        """Return the captured producer response for a submission."""
        self.requests.append((path, json))
        return self.response()

    def get(self, path):
        """Return the captured producer response for a read."""
        self.requests.append((path, None))
        return self.response()

    def response(self):
        """Build a partial job retaining typed canonical assessments."""
        return {
            "id": self.bundle["execution_id"],
            "tenant_id": self.bundle["tenant_id"],
            "user_id": self.bundle["tenant_id"],
            "config_id": self.bundle["tenant_id"],
            "execution_type": "extraction_evaluate",
            "status": "partial",
            "progress_count": 7,
            "total_count": 7,
            "assessment_bundle": self.bundle,
            "results": {"trials": [{"trial_id": "baseline"}, {"trial_id": "repeat"}]},
        }


def test_public_create_get_preserve_extraction_results_and_canonical_rules():
    """Retain repeat membership and deterministic receipts on public reads."""
    wire = fixture()
    transport = Transport(wire)
    jobs = JobsClient(transport)
    payload = {"schema_version": 1, "dataset_id": "fictional", "cases": []}
    result = jobs.create(
        execution_type="extraction_evaluate",
        data=payload,
        client_request_id=wire["execution_id"],
    )
    assert transport.requests[0][1]["checkpoint_data"] == payload
    assert result.execution_type == "extraction_evaluate"
    assert result.assessment_bundle.model_dump(mode="json") == wire
    assert jobs.get(result.id).results["trials"] == [{"trial_id": "baseline"}, {"trial_id": "repeat"}]
    repeat_sets = [a for a in result.assessment_bundle.assessments if a.subject_kind == "repeat_set"]
    assert len(repeat_sets) == 2
    assert all(len(a.inputs) == 3 for a in repeat_sets)


def test_wait_returns_partial_results_instead_of_polling_until_timeout(monkeypatch):
    """Stop waiting while preserving the partial status."""
    jobs = JobsClient(Transport(fixture()))
    monkeypatch.setattr("genflux.jobs.time.sleep", lambda *_args: pytest.fail("Partial is already terminal"))
    result = jobs.wait(fixture()["execution_id"])
    assert result.status == "partial"
    assert not result.is_completed
    assert result.assessment_bundle is not None


@pytest.mark.parametrize("mutation", ["cost", "provider", "model", "unsent", "non_extraction"])
def test_deterministic_rules_cannot_claim_model_usage(mutation):
    """Reject broadened local receipts and invented remote usage."""
    wire = fixture()
    attempt = next(
        a
        for result in wire["assessments"]
        for a in result["attempts"]
        if a["evaluator"] == "screen_extraction_rules_v1"
    )
    if mutation == "cost":
        attempt["usage"]["cost_usd"] = 0.01
    elif mutation == "provider":
        attempt["provider_call_id"] = wire["execution_id"]
    elif mutation == "model":
        attempt["requested_model"] = "jev-latest"
    elif mutation == "unsent":
        attempt["status"] = "not_sent"
    else:
        assessment = next(a for a in wire["assessments"] if attempt in a["attempts"])
        assessment["metric"]["namespace"] = "quality"
    with pytest.raises(ValueError):
        parse_assessment_bundle(wire)
