# generated by datamodel-codegen:
#   filename:  assessment-v3.schema.json
#   version:   0.33.0

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import AwareDatetime, BaseModel, ConfigDict, Field, RootModel


class Confidence(RootModel[float]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[float, Field(ge=0.0, le=1.0, title='Confidence')]


class InputHash(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[str, Field(pattern='^[a-f0-9]{64}$', title='Input Hash')]


class ProviderScaleMaximum(RootModel[float]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[float, Field(gt=0.0, title='Provider Scale Maximum')]


class RubricHash(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[str, Field(pattern='^[a-f0-9]{64}$', title='Rubric Hash')]


class CostUsd(RootModel[float]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[float, Field(ge=0.0, title='Cost Usd')]


class InputTokens(RootModel[int]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[int, Field(ge=0, title='Input Tokens')]


class OutputTokens(RootModel[int]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[int, Field(ge=0, title='Output Tokens')]


class AttemptUsage(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    cost_source: Annotated[str | None, Field(title='Cost Source')] = None
    cost_usd: Annotated[CostUsd | None, Field(title='Cost Usd')] = None
    input_tokens: Annotated[InputTokens | None, Field(title='Input Tokens')] = None
    measurement: Annotated[
        Literal['known', 'unknown', 'not_incurred'], Field(title='Measurement')
    ]
    output_tokens: Annotated[OutputTokens | None, Field(title='Output Tokens')] = None
    price_revision: Annotated[str | None, Field(title='Price Revision')] = None


class ContextEvidence(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    context_id: Annotated[UUID, Field(title='Context Id')]
    sequence: Annotated[int, Field(ge=0, title='Sequence')]
    source_kind: Annotated[
        Literal['retrieved', 'reference'], Field(title='Source Kind')
    ]
    text: Annotated[str, Field(title='Text')]


class EvidenceSpan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    context_id: Annotated[UUID | None, Field(title='Context Id')] = None
    end: Annotated[int, Field(gt=0, title='End')]
    field: Annotated[
        Literal['question', 'answer', 'ground_truth', 'context'], Field(title='Field')
    ]
    input_id: Annotated[UUID, Field(title='Input Id')]
    start: Annotated[int, Field(ge=0, title='Start')]


class ExplanationIssue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    claim: Annotated[str, Field(min_length=1, title='Claim')]
    evidence: Annotated[list[EvidenceSpan], Field(min_length=1, title='Evidence')]


class ExplanationRevision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    assessment_id: Annotated[UUID, Field(title='Assessment Id')]
    assessment_revision: Annotated[int, Field(ge=1, title='Assessment Revision')]
    explanation_id: Annotated[UUID, Field(title='Explanation Id')]
    generation_attempt_id: Annotated[
        UUID | None, Field(title='Generation Attempt Id')
    ] = None
    input_set_hash: Annotated[
        str, Field(pattern='^[a-f0-9]{64}$', title='Input Set Hash')
    ]
    issues: Annotated[list[ExplanationIssue], Field(title='Issues')]
    message_code: Annotated[str, Field(min_length=1, title='Message Code')]
    prompt_version: Annotated[str | None, Field(title='Prompt Version')] = None
    revision: Annotated[int, Field(ge=1, title='Revision')]
    status: Annotated[
        Literal[
            'supported_issue',
            'assessment_conflict',
            'insufficient_evidence',
            'generation_error',
            'not_requested',
        ],
        Field(title='Status'),
    ]


class TargetRevision(RootModel[str]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[str, Field(min_length=1, title='Target Revision')]


class TurnIndex(RootModel[int]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[int, Field(ge=0, title='Turn Index')]


class InputPayload(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    answer: Annotated[str | None, Field(title='Answer')] = None
    client_case_id: Annotated[str | None, Field(title='Client Case Id')] = None
    collection_status: Annotated[
        Literal['collected', 'error', 'unavailable'], Field(title='Collection Status')
    ]
    contexts: Annotated[list[ContextEvidence] | None, Field(title='Contexts')] = None
    ground_truth: Annotated[str | None, Field(title='Ground Truth')] = None
    question: Annotated[str, Field(title='Question')]
    repeat_index: Annotated[int | None, Field(ge=0, title='Repeat Index')] = 0
    rule_id: Annotated[str | None, Field(title='Rule Id')] = None
    rule_revision: Annotated[str | None, Field(title='Rule Revision')] = None
    scenario_id: Annotated[str | None, Field(title='Scenario Id')] = None
    target_revision: Annotated[
        TargetRevision | None, Field(title='Target Revision')
    ] = None
    turn_index: Annotated[TurnIndex | None, Field(title='Turn Index')] = None


class InputReference(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    context_ids: Annotated[list[UUID] | None, Field(title='Context Ids')] = None
    input_hash: Annotated[str, Field(pattern='^[a-f0-9]{64}$', title='Input Hash')]
    input_id: Annotated[UUID, Field(title='Input Id')]
    role: Annotated[
        Literal['primary', 'repeat', 'turn', 'reference'], Field(title='Role')
    ]
    sequence: Annotated[int, Field(ge=0, title='Sequence')]


class InputSnapshot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    answer_id: Annotated[UUID, Field(title='Answer Id')]
    captured_at: Annotated[AwareDatetime, Field(title='Captured At')]
    case_id: Annotated[UUID, Field(title='Case Id')]
    execution_id: Annotated[UUID, Field(title='Execution Id')]
    input_hash: Annotated[str, Field(pattern='^[a-f0-9]{64}$', title='Input Hash')]
    input_id: Annotated[UUID, Field(title='Input Id')]
    payload: InputPayload
    schema_version: Annotated[Literal[1], Field(title='Schema Version')] = 1
    tenant_id: Annotated[UUID, Field(title='Tenant Id')]


class MeasuredOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    acceptance_verdict: Annotated[
        Literal['pass', 'fail', 'undetermined', 'not_applicable'],
        Field(title='Acceptance Verdict'),
    ]
    measurement_status: Annotated[
        Literal['measured'], Field(title='Measurement Status')
    ]
    quality_band: Annotated[
        Literal['good', 'review', 'poor'], Field(title='Quality Band')
    ]
    reason_code: Annotated[str | None, Field(title='Reason Code')] = None
    review_state: Annotated[
        Literal['not_assessed', 'required', 'resolved'], Field(title='Review State')
    ]
    score: Annotated[float, Field(ge=0.0, le=1.0, title='Score')]


class AcceptanceMinimum(RootModel[float]):
    model_config = ConfigDict(
        frozen=True,
    )
    root: Annotated[float, Field(ge=0.0, le=1.0, title='Acceptance Minimum')]


class MetricDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    acceptance_minimum: Annotated[
        AcceptanceMinimum | None, Field(title='Acceptance Minimum')
    ] = None
    acceptance_operator: Annotated[
        Literal['gte', 'gt'] | None, Field(title='Acceptance Operator')
    ] = 'gte'
    definition_revision: Annotated[
        str, Field(pattern='^[a-f0-9]{64}$', title='Definition Revision')
    ]
    good_minimum: Annotated[float, Field(ge=0.0, le=1.0, title='Good Minimum')]
    methodology: Annotated[str, Field(min_length=1, title='Methodology')]
    metric_id: Annotated[str, Field(min_length=1, title='Metric Id')]
    namespace: Annotated[str, Field(min_length=1, title='Namespace')]
    required_inputs: Annotated[list[str], Field(title='Required Inputs')]
    review_minimum: Annotated[float, Field(ge=0.0, le=1.0, title='Review Minimum')]
    rubric_hash: Annotated[RubricHash | None, Field(title='Rubric Hash')] = None
    rubric_version: Annotated[str | None, Field(title='Rubric Version')] = None
    score_direction: Annotated[
        Literal['higher_is_better'], Field(title='Score Direction')
    ] = 'higher_is_better'


class UnmeasuredOutcome(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    acceptance_verdict: Annotated[None, Field(title='Acceptance Verdict')] = None
    measurement_status: Annotated[
        Literal['error', 'skipped', 'unavailable'], Field(title='Measurement Status')
    ]
    quality_band: Annotated[None, Field(title='Quality Band')] = None
    reason_code: Annotated[str, Field(min_length=1, title='Reason Code')]
    review_state: Annotated[Literal['not_assessed'], Field(title='Review State')] = (
        'not_assessed'
    )
    score: Annotated[None, Field(title='Score')] = None


class AssessmentAttempt(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    attempt_id: Annotated[UUID, Field(title='Attempt Id')]
    attempt_number: Annotated[int, Field(ge=1, title='Attempt Number')]
    confidence: Annotated[Confidence | None, Field(title='Confidence')] = None
    error_code: Annotated[str | None, Field(title='Error Code')] = None
    evaluator: Annotated[str, Field(min_length=1, title='Evaluator')]
    execution_mode: Annotated[
        Literal['quick', 'batch', 'policy', 'redteam', 'local_mock'],
        Field(title='Execution Mode'),
    ]
    input_hash: Annotated[InputHash | None, Field(title='Input Hash')] = None
    probabilities: Annotated[dict[str, float] | None, Field(title='Probabilities')] = (
        None
    )
    provider_call_id: Annotated[UUID | None, Field(title='Provider Call Id')] = None
    provider_request_id: Annotated[str | None, Field(title='Provider Request Id')] = (
        None
    )
    provider_scale_maximum: Annotated[
        ProviderScaleMaximum | None, Field(title='Provider Scale Maximum')
    ] = None
    provider_score: Annotated[float | None, Field(title='Provider Score')] = None
    provider_score_direction: Annotated[
        Literal['higher_is_better', 'lower_is_better'] | None,
        Field(title='Provider Score Direction'),
    ] = None
    purpose: Annotated[
        Literal['judge', 'explanation', 'target'], Field(title='Purpose')
    ]
    requested_model: Annotated[str | None, Field(title='Requested Model')] = None
    resolved_model: Annotated[str | None, Field(title='Resolved Model')] = None
    rubric_hash: Annotated[RubricHash | None, Field(title='Rubric Hash')] = None
    rubric_version: Annotated[str | None, Field(title='Rubric Version')] = None
    status: Annotated[
        Literal['measured', 'error', 'unknown', 'not_sent'], Field(title='Status')
    ]
    transport_version: Annotated[str | None, Field(title='Transport Version')] = None
    usage: AttemptUsage


class AssessmentRevision(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    answer_id: Annotated[UUID, Field(title='Answer Id')]
    assessment_id: Annotated[UUID, Field(title='Assessment Id')]
    attempts: Annotated[list[AssessmentAttempt], Field(title='Attempts')]
    case_id: Annotated[UUID, Field(title='Case Id')]
    execution_id: Annotated[UUID, Field(title='Execution Id')]
    explanation: ExplanationRevision
    inputs: Annotated[list[InputReference], Field(min_length=1, title='Inputs')]
    metric: MetricDefinition
    outcome: Annotated[
        MeasuredOutcome | UnmeasuredOutcome,
        Field(discriminator='measurement_status', title='Outcome'),
    ]
    revision: Annotated[int, Field(ge=1, title='Revision')]
    schema_version: Annotated[Literal[3], Field(title='Schema Version')]
    selected_attempt_id: Annotated[UUID | None, Field(title='Selected Attempt Id')] = (
        None
    )
    subject_key: Annotated[str, Field(min_length=1, title='Subject Key')]
    subject_kind: Annotated[
        Literal['answer', 'repeat_set', 'rule', 'turn'], Field(title='Subject Kind')
    ]
    tenant_id: Annotated[UUID, Field(title='Tenant Id')]


class AssessmentBundle(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    assessments: Annotated[list[AssessmentRevision], Field(title='Assessments')]
    execution_id: Annotated[UUID, Field(title='Execution Id')]
    inputs: Annotated[list[InputSnapshot], Field(title='Inputs')]
    schema_version: Annotated[Literal[3], Field(title='Schema Version')]
    tenant_id: Annotated[UUID, Field(title='Tenant Id')]
