# generated by datamodel-codegen:
#   filename:  accepted-assessment-plan-v1.schema.json
#   version:   0.33.0

from __future__ import annotations

from typing import Annotated, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class AcceptedAssessmentSlot(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    client_case_id: Annotated[str, Field(min_length=1, title='Client Case Id')]
    input_condition_key: Annotated[str | None, Field(title='Input Condition Key')] = (
        None
    )
    requested_metric: Annotated[str, Field(min_length=1, title='Requested Metric')]
    slot_id: Annotated[str, Field(min_length=1, title='Slot Id')]
    subject_key: Annotated[str, Field(min_length=1, title='Subject Key')]
    subject_kind: Annotated[
        Literal['answer', 'repeat_set', 'rule', 'turn'], Field(title='Subject Kind')
    ]


class AcceptedAssessmentPlan(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
        frozen=True,
    )
    execution_id: Annotated[UUID, Field(title='Execution Id')]
    plan_id: Annotated[UUID, Field(title='Plan Id')]
    revision: Annotated[Literal[1], Field(title='Revision')] = 1
    schema_version: Annotated[Literal[1], Field(title='Schema Version')] = 1
    slots: Annotated[list[AcceptedAssessmentSlot], Field(min_length=1, title='Slots')]
    state: Annotated[Literal['accepted'], Field(title='State')] = 'accepted'
    tenant_id: Annotated[UUID, Field(title='Tenant Id')]
